### ISSUE TITLE
Event-loop Node.js - Vendredi 16 - 21h - 22h30

### ISSUE THREAD

**Issue by fraxken** [fraxken/frax_school#1]
Une session disponible pour le cours Event-loop Node.js vendredi 16 à 21h/22h30.

Trois places disponibles.

Pour vous inscrire merci de juste laisser un message sur l'issue !

**Comment by dimensi0n** [comment]
Je suis la 😄

**Comment by Kawacrepe** [comment]
Salut! Je suis partant aussi !

**Comment by dimensi0n** [comment]
@Kawacrepe yeaaah

**Comment by nolanrigo** [comment]
Puis-je participer ?

**Comment by fraxken** [comment]
Cours terminé ! N'hésitez pas à laisser un commentaire pour dire si vous étiez satisfait du cours ou non :)

**Comment by dimensi0n** [comment]
Encore merci pour ce fabuleux cours !

**Comment by nolanrigo** [comment]
Très bonne intro au sujet 👍 , avec des liens pour poursuivre de son côté, au top 🎉

**Comment by Kawacrepe** [comment]
Cours très intéressant, merci !
